"""Add analytics columns to subscribed_users

Revision ID: 410e0d0ed473
Revises: 54fea013d87f
Create Date: 2025-05-21 12:31:03.045447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410e0d0ed473'
down_revision = '54fea013d87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribed_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analytics_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qr_generated', sa.Integer(), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('design', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('analytics', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qr_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_confirm_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email_confirm_token',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('qr_count')
        batch_op.drop_column('analytics')
        batch_op.drop_column('design')

    with op.batch_alter_table('subscribed_users', schema=None) as batch_op:
        batch_op.drop_column('qr_generated')
        batch_op.drop_column('analytics_used')

    # ### end Alembic commands ###
